l_english:
 ADD_CONVEYOR_LINE_BUTTON_DESC:0 "Zahájí paralelní výcvik další divize typu $CONVEYOR|H$.\n\n§GShift+klik§! přidá 5 divizí"
 ADD_CONVEYOR_LINE_BUTTON_LABEL:0 "Přidat divizi"
 AIR_DEPLOYMENT:0 "§TNasazení letectva§!"
 CANCEL_CONVEYOR_TOOLTIP:0 "§RZrušit§! výcvik všech divizí."
 CANNOT_DELETE_SPECIAL_TEMPLATES:0 "Nelze odstranit speciální šablony."
 CANT_CHANGE_DUE_TO_DIVISION_CAP:0 "Nelze změnit na tuto šablonu — překročilo by to limit počtu divizí."
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "Nelze změnit na tuto šablonu — překročilo by to limit speciálních sil."
 CONVEYOR_CANCEL_DESC:0 "Opravdu chcete §Rzrušit§! výcvik všech divizí ve frontě?"
 CONVEYOR_CANCEL_TITLE:0 "§RZrušit§! výcvik"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN:0 "§RNedostatek personálu pro výcvik§!"
 CONVEYOR_CAN_NOT_TRAIN:0 "§RNedostatek vybavení pro výcvik§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§RNedostatek personálu nebo vybavení pro výcvik $DIVS|H$ divizí§!"
 CONVEYOR_COLLAPSE_DESC:0 "§GKlikni§! pro sbalení"
 CONVEYOR_EQUIPMENT_NEED:0 "Požadované vybavení:"
 CONVEYOR_EXPAND_DESC:0 "§GKlikni§! pro rozbalení"
 CONVEYOR_GENERIC_NAME_EDIT_DESC:0 "Napište zde pro změnu obecného názvu nasazení."
 CONVEYOR_GROUP_ASSIGN_DESC:0 "§GKlikni§! pro přiřazení k rozkazu.\n§GPravý klik§! pro zrušení přiřazení."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "Nasazení musí mít cílovou lokaci pro přiřazení ke skupině."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "Nasazení musí mít alespoň jeden rozkaz v rámci válčiště pro přiřazení ke skupině."
 CONVEYOR_HAS_BAD_LOCATION:0 "Cílová oblast je nyní §Rneplatná§! pro nasazení."
 CONVEYOR_HIGH_PRIORITY_DESC:0 "Vysoká priorita doplňování"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "Opravdu chceš §Rzrušit§! výcvik této divize?"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "Opravdu chceš §Rzrušit§! výcvik této divize?\n(Divize bude také §Rodstraněna§!)"
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE:0 "§RZrušit§! výcvik"
 CONVEYOR_LINE_CANCEL_DESC:0 "§RZrušit§! výcvik této divize."
 CONVEYOR_LINE_DEPLOY_DESC:0 "§GKlikni§! pro okamžité nasazení této divize."
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC:0 "Napište zde pro změnu aktuálního prefixu linky."
 CONVEYOR_LINE_SERIES_BASE:0 "$CURRENT$/$TARGET$"
 CONVEYOR_LOW_PRIORITY_DESC:0 "Nízká priorita doplňování"
 CONVEYOR_MANPOWER_NEED:0 "Požadovaný personál: $AMOUNT|H$"
 CONVEYOR_MEDIUM_PRIORITY_DESC:0 "Střední priorita doplňování"
 CONVEYOR_MOVE_DOWN:0 "§GKlik§! k posunutí dolů\n§GShift+Klik§! k posunutí na konec"
 CONVEYOR_MOVE_UP:0 "§GKlik§! k posunutí nahoru\n§GShift+Klik§! k posunutí na začátek"
 CONVEYOR_SERIES_AMOUNT_DESC:0 "To je počet divizí, které každá linka vycvičí předtím, než bude ukončena.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC:0 "Aktuální série výcviku divizí v této lince."
 CONVEYOR_SERIES_DECREASE_DESC:0 "Snížení počtu sériového výcviku divizí, které každá linka dokončí.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SERIES_INCREASE_DESC:0 "Zvýšení počtu sériového výcviku divizí, které každá linka dokončí.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SET_COLONIAL_LOCATION_DESC:0 "§GKlik§! pro nastavení místa nasazení pro tuhle divizi ve výcviku.\n§GPravý klik§! pro resetování místa.\n§YToto je koloniální šablona a lze ji nasadit pouze v zemi původu!§!"
 CONVEYOR_SET_LOCATION_DESC:0 "§GKlik§! pro nastavení místa nasazení pro tuhle divizi ve výcviku.\n§GPravý klik§! pro resetování výběru."
 CONVEYOR_SET_LOCATION_NOT_SET:0 "§RNevybráno žádné místo§!"
 CONVEYOR_TEMPLATE_ICON_DESC:0 "Zde probíhá výcvik divizí dle šablony $TEMPLATE|H$."
 CONVEYOR_TRAINING_NOT_FINISHED:0 " Výcvik této linky ještě není dokončen."
 COPY:0 "Kopírovat"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF:0 "Znovuzařadit"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF_DESC:0 "§GKlik§! pro znovuzařazení této šablony, což označí, že je aktivní."
 DECOMMISSION_TEMPLATE_TOGGLE_ON:0 "Vyřadit"
 DECOMMISSION_TEMPLATE_TOGGLE_ON_DESC:0 "§GKlik§! pro vyřazení této šablony, což označí, že je vyřazena."
 DELETE_TEMPLATE:0 "§RVymazat§! šablonu ze seznamu."
 DELETE_TEMPLATE_DESC:0 "Opravdu chcete tuto šablonu smazat?"
 DELETE_TEMPLATE_TITLE:0 "Smazat šablonu"
 DEPLOY:0 "Nasadit"
 DEPLOYMENT_ADD_TEMPLATE:0 "Trénovat"
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "Nelze trénovat novou divizi speciálních jednotek."
 DEPLOYMENT_CURRENT_LEVEL:0 "Aktuálně je divize ve výcviku na úrovni $NUMBER$ ( $LEVEL|%Y0$ )"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "Nábor a nasazení"
 DEPLOYMENT_DEPLOY_LABEL:0 "Nasadit"
 DEPLOYMENT_DESIGNER:0 "Návrhář divize"
 DEPLOYMENT_DIVISION_LABEL:0 "Divize"
 DEPLOYMENT_EQUIPMENT:0 "Vybavení: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_CHANGE:0 "$NAME$: $VALUE$"
 DEPLOYMENT_EQUIPMENT_DESC:0 "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC:0 "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT:0 "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL:0 "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "Jako §Hexilová vláda§! musíme kontrolovat §Hhlavní město§!, abychom mohli trénovat nové divize."
 DEPLOYMENT_EXPERIENCE_DESC:0 "\nPokud je výcvik dokončen, tato divize získá dostatečné zkušenosti na to, aby byla nasazena na úrovni $NUMBER$ ( $MAXLEVEL|%Y0$ ) s bojovým modifikátorem $EFFECT|+=%0$"
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC:0 "\nPokud je tato divize plně vybavena, výcvik bude dokončen §Y$DATE$§!"
 DEPLOYMENT_HIGH_PRIORITY_DESC:0 "Vysoká priorita vybavení"
 DEPLOYMENT_HOW_TO_DESC:0 "Vyberte divize ve výcviku ze seznamu a poté §Gklikněte§! na zvýrazněné provincie na mapě pro jejich nasazení.\n§gDivize nasazené s neúplným vybavením je získají prostřednictvím žádostí o posily.\nZvažte, že divize nasazené příliš brzo nedostanou patřičný výcvik.§!"
 DEPLOYMENT_LEND_LEASE_COUNTRY:0 "Lend-Lease: $COUNTRY$"
 DEPLOYMENT_LINES_HIT_THE_CAP:0 "Můžeme vycvičit maximálně $CAP|*H$ mužů.\nOmezeno maximálním počtem personálu v poli ( $RATIO|H0%$ z $INFIELD|*H$. Minimálně: $MINPOSSIBLE|*H$ mužů)"
 DEPLOYMENT_LINES_HIT_THE_DIVISION_CAP:0 "§RDosáhnuto maxima pro tuhle šablonu§! \n"
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME:0 "§HZvolte další historické jméno.§!\n§GKlikněte§! pro otevření seznamu všech historických jmen, která jsou stále k dispozici. Je možné změnit skupinu jmen úpravou šablony."
 DEPLOYMENT_LINE_EDIT_NAME:0 "Pro použití vlastního názvu §Gklikněte§! a napište."
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL:0 "§HVymazat vlastní název§!\nSnažíme se obnovit původně přiřazený název, pokud není již obsazen."
 DEPLOYMENT_LINE_OUT_OF_NAMES:0 "§gNedostatek historických jmen.§!"
 DEPLOYMENT_LOW_PRIORITY_DESC:0 "Nízká priorita vybavení"
 DEPLOYMENT_MANPOWER_DESC:0 "Personál: $VALUE|Y0$ ( Max $MAX|Y0$ )"
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "To ponechává místo pro $TRAINABLE|Y$ divizí používajících tuto šablonu."
 DEPLOYMENT_MEDIUM_PRIORITY_DESC:0 "Střední priorita vybavení"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT:0 "§RNelze§! nasadit divizi, která nemá žádné vybavení.\nPočkejte, dokud tato divize ve výcviku nezíská nějaké vybavení."
 DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP:0 "§RNelze§! nasadit divizi, která by překročila limit pro danou šablony divize"
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER:0 "§RNelze§! nasadit divizi, která nemá žádné muže."
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES:0 "§RNelze§! nasadit divizi, která by překročila náš limit speciálních jednotek"
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING:0 "§RNelze§! nasadit divizi, která není vycvičena alespoň na $VALUE|1H%$ (Aktuálně $CURRENT|1R%$)"
 DEPLOYMENT_PRIORITY_LABEL:0 "Priorita"
 DEPLOYMENT_PROGRESS_LABEL:0 "Pokrok"
 DEPLOYMENT_RAIDS_DESC: "§YNálety§!\n§TNastavte prioritu vybavení pro přípravu náletů§!"
 DEPLOYMENT_RAIDS_EMPTY:0 "§GŽádna aktuální požadavka pro nálet.§!"
 DEPLOYMENT_REMOVE_DIVISION:0 "Zrušit divizi"
 DEPLOYMENT_REQUIREMENT:0 "$NAME$: $AMOUNT$"
 DEPLOYMENT_TEMPLATE_ITEM_ADD:0 "§GKlikněte pro přidání do fronty pro výcvik§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY:0 "§GKlikněte pro zkopírování do našich nasaditelných šablon§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§GKlikněte pro úpravu šablony divize§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW:0 "§GKlikněte pro zobrazení šablony divize§!"
 DEPLOYMENT_TEMPLATE_LABEL:0 "Šablony"
 DEPLOYMENT_TRAINING:0 "Výcvik: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC:0 "/ $VALUE|H%0$ ( Maximální úroveň výcviku závisí na množství vybavení )"
 DEPLOYMENT_VIEW_SPECIAL_FORCES_DETAILS: "$USED$/$CAP$"
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP:0 "Nemá žádné divize ve výcviku připravené k okamžitému §Rnasazení§!."
 DEPLOY_CONVEYOR_TOOLTIP:0 "§GKlikni§! pro okamžité nasazení všech divizí vo výcviku."
 DIVISIONS_QUEUED:0 "Počet divizí: $N$"
 DIVISION_CAP_LIMIT_DESC:0 "Tato divize využívá limit šablony, protože to je nejnižší limit."
 DIVISION_CAP_OF_TEMPLATE:0 "Tato šablona má limit na úrovni $NUM|Y$."
 DIVISION_CAP_USAGE_DESC:0 "V současnosti nasazujete $USED|Y$ a ve výcviku se nachází $IN_TRAINING|Y$ z našich $CAP|Y$ povolených divizí pro $NAME|Y$"
 DIVISION_DESIGNER_RENAME:0 "Přejmenovat"
 DIVISION_DESIGNER_UPDATE:0 "Aktualizovat"
 DIVISION_EQUIPMENT:1 "Vybavení"
 DIVISION_QUEUED:0 "Počet divizí: $N$"
 DO_NOT_CONTAINS_TEMPLATE:0 "§RTuto šablonu nelze odstranit. Země ji nevlastní.§!"
 EDIT:0 "Upravit"
 EXCEEDING_DIVISION_CAP:0 "§RPřekročena kapacita pro tuto šablonu divize.§!"
 GARRISONS:0 "Posádky"
 GARRISONS_DESC:1 "§YPosádky§!\n§TNastavte prioritu vybavení určeného pro posádky§!"
 GARRISONS_EMPTY:0 "§GAktuálně nejsou žádné požadavky pro posádky.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§RTuto šablonu nelze odstranit, protože $AMOUNT|H$ divizí přechází na novou šablonu (čekají na vybavení odpovídající nové šabloně).§!"
 HAS_ARMIES_WITH_TEMPLATE:0 "§RTuto šablonu nelze odstranit, protože ji právě používá $AMOUNT|H$ divizí.§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "§RNelze odstranit§! tuto šablonu ze země. Země má $AMOUNT|H$ nasazených divizí využívajících tuto šablonu."
 HAS_EXILE_TRANSFER_WITH_TEMPLATE:0 "§RTuto šablonu nelze odstranit, protože ji používá $AMOUNT|H$ divizí ustupujících do exilu.§!"
 HAS_GARRISON_WITH_TEMPLATE:0 "§RTuto šablonu nelze odstranit, protože je používána jako šablona posádek pro okupovaná území.§!"
 LAND_DEPLOYMENT:0 "§TNasazení pozemních sil§!"
 MISSING_SPECIAL_FORCES_CAP:0 "§RNedostatečná kapacita pro speciální jednotky§!"
 NAVAL_DEPLOYMENT:0 "§TNasazení námořnictva§!"
 NEW_EQUIPMENT_ALLOWED:0 "Používat nové vybavení"
 NEW_GROUP_ADDITIONAL_COST:0 "Nová skupina $VALUE|H0$£army_experience£"
 NO_SPECIAL_FORCES:0 "Tato šablona neobsahuje žádné speciální jednotky"
 ONLY_ONE_TEMPLATE_LEFT:0 "Nelze odstranit poslední šablonu."
 OPERATIONS_DESC:0 "§YOperace§!\n§TUprav prioritu vybavení pro přípravu a provádění operací§!"
 OPERATIONS_EMPTY:0 "§GAktuálně nejsou žádné požadavky pro operace.§!"
 REGIMENTS_SELECTION_CANCEL:0 "Zpět"
 REINFORCEMENT:0 "Posily"
 REINFORCEMENT_DESC:1 "§YPosily§!\n§TNastavte prioritu pro vybavení, které bude preferovat posily pro divize v terénu oproti výcviku a modernizaci§!"
 REINFORCEMENT_EMPTY:0 "§GAktuálně nejsou žádné požadavky na vybavení.§!"
 SHOW_DECOMMISSIONED_TEMPLATES:0 "Zobrazit §Hvyřazené šablony§!"
 SPECIAL_FORCES_CAP_DESC:0 "V současnosti máme nasazeno $USED|Y$ a ve výcviku $IN_TRAINING|Y$ z povolené kapacity $CAP|Y$ speciálních jednotek."
 SPECIAL_FORCES_CAP_LIMIT_DESC:0 "Tato divize využívá limit pro speciální jednotky, protože se jedná o nejnižší dostupný limit."
 SPECIAL_FORCES_IN_TEMPLATE:0 "Tato šablona využívá $NUM|Y$ kapacity speciálních jednotek."
 TEMPLATE_PRIO_0:0 "Zálohy"
 TEMPLATE_PRIO_0_DESC:0 "Jednotky s touto šablonou budou po nasazení dostávat vybavení jako poslední s nejnižší prioritou. Vhodné pro jednotky na obranu základen a podobně."
 TEMPLATE_PRIO_1:0 "Výchozí"
 TEMPLATE_PRIO_1_DESC:0 "Jednotky s touto šablonou mají po nasazení běžnou prioritu při zásobování a doplňování vybavení."
 TEMPLATE_PRIO_2:0 "Elita"
 TEMPLATE_PRIO_2_DESC:0 "Jednotky s touto šablonou budou po nasazení vybaveny přednostně. Použijte je pro své nejlepší muže tam, kde mohou být nejúčinnější."
 TIMED_ACTIVITY_ALERT_TITLE:0 "$NAME|H$ proti zemi $COUNTRY|H$"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC:0 "§GBylo získáno maximální množství vybavení.§!"
 TIMED_ACTIVITY_ENTRY_DESC:0 "§TUrčete prioritu vybavení, které bude použito na podporu této diplomatické aktivity.§!"
 TIMED_ACTIVITY_TITLE:0 "$NAME$ proti zemi $COUNTRY$"
 TRAINING_HALTED:0 "Výcvik byl pozastaven\n"
 UPGRADES:0 "Modernizace"
 UPGRADES_DESC:1 "§YModernizace§!\n§TNastavte prioritu pro vybavení, které jde na modernizaci aktivních divizí ve srovnání s divizemi ve výcviku a posilami§!"
 UPGRADES_EMPTY:0 "§GŽádné aktuální požadavky na modernizaci.§!"
 VIEW:0 "Zobrazit"
 group_armor_combat_support_title:0 "Obrněné podpůrné prapory"
 group_armor_title:0 "Obrněné prapory"
 group_combat_support_title:0 "Bojové podpůrné prapory"
 group_infantry_title:0 "Pěší prapory"
 group_mobile_combat_support_title:0 "Mobilní podpůrné prapory"
 group_mobile_title:0 "Mobilní prapory"
 group_support_title:1 "Podpůrné roty"
